---
title: "hw6"
author: "cyber-atlas"
date: "April 23, 2019"
output: html_document
---
```{r}
library('ggplot2')
library(dplyr)
library(tidyverse)
# install.packages("ggrepel")
library("ggrepel")
# install.packages('magrittr')
library('magrittr')
```

Get the Best In Show dataset

```{r}
BIS<-readxl::read_xlsx('KIB.xlsx', sheet='Best in show full sheet')
head(BIS,10)
```

```{r}
BIS <- BIS %>%  select(c(1,3,5,6,12,32))

head(BIS,10)

```
Had to show the first 10 rows because there was so much garbge data in it. Looks like the first few rows aren't needed and there's extra uncessary columns. Let's get rid of that.

```{r}
BIS <- BIS[4:nrow(BIS),]
head(BIS,10)
```

Clean up the names and make the data the correct type

```{r}
names(BIS)[1] <- 'Breed'
BIS$Breed %<>% factor 
names(BIS)[2] <- 'Category'
BIS$Category %<>% factor
names(BIS)[3] <- 'Score'
BIS$Score <- as.numeric(BIS$Score)
names(BIS)[4] <- 'Popularity'
BIS$Popularity <- as.numeric(BIS$Popularity)
names(BIS)[5] <- 'Intelligence'
# BIS$Intelligence <- as.numeric(BIS$Intelligence)
names(BIS)[6] <- 'Size'
BIS$Size %<>% factor
levels(BIS$Size)
#They're not in the correct order, let's fix that
BIS$Size <- factor(BIS$Size, levels=c("small", "medium", "large"))

#Get rid of all na's
BIS<-na.omit(BIS)

BIS$Intelligence[BIS$Intelligence >= .5] <- "Clever"
BIS$Intelligence[BIS$Intelligence < .5] <- "Dumb"
#Make it factor here bc of our changes
BIS$Intelligence %<>% factor
#Let's look at the dataframe now
head(BIS) 
```

Now that that the DF is much cleaner, let's *attempt to* plot it like the pretty infographic. 


```{r}


ggplot(data=BIS, aes(x=Score, 
                     y= Popularity, 
                     shape= Intelligence, 
                     size=Size, 
                     color=Category, 
                     label=Breed)
       )+
  geom_point(alpha=0.65)+
  ylim((max(BIS$Popularity)+2),(min(BIS$Popularity))-2)+
  xlim((min(BIS$Score)-.2),(max(BIS$Score)+.2))+
  geom_vline( xintercept = 
                 ((max(BIS$Score)-min(BIS$Score))/2)+min(BIS$Score)
              )+
  geom_hline(yintercept = 
               ((max(BIS$Popularity)-min(BIS$Popularity))/2) + min(BIS$Popularity)
               )+
  ggtitle("Best in Show: The Ultimate Data Dog")+
  geom_text_repel(size=1, segment.size = .1) +
  annotate("text", label = "Inexplicably Overrated", x = 1.1, y = -.1, size = 2, alpha=0.5)+
  annotate("text", label = "Hot Dogs!", x = 3.5, y = -.1, size = 2, alpha=0.5)+
  annotate("text", label = "Rightly Ignored", x = 1.1, y = 150, size = 2, alpha=0.5)+
  annotate("text", label = "Overlooked Treasures", x = 3.5, y =150, size = 2, alpha=0.5)+
  annotate("text", label = "Our Data Score", x = 1.0, y = 82, size = 2) +
  annotate("text", label = "Popularity", x = 2.3, y = -.2, size = 2)+
    theme_void()+
  theme(panel.background = element_rect(fill = '#f7f1e1', colour = 'grey'))+
 scale_fill_brewer(palette="Set1")
  

```



